version: '3.8'

services:
  coolify:
    image: $COLLIFY_IMAGE
    restart: always
    container_name: coolify
    privileged: true
    environment:
      - COOLIFY_APP_ID=${COOLIFY_APP_ID}
      - COOLIFY_IS_ON=${COOLIFY_IS_ON}
      - COOLIFY_SECRET_KEY=${COOLIFY_SECRET_KEY}
      - COOLIFY_AUTO_UPDATE=${COOLIFY_AUTO_UPDATE}
      - COOLIFY_DATABASE_URL=file:${COOLIFY_DATABASE_URL}
      - COOLIFY_WHITE_LABELED=${COOLIFY_WHITE_LABELED}
      - COOLIFY_WHITE_LABELED_ICON=${COOLIFY_WHITE_LABELED_ICON}
    ports:
      - '3000:3000'
      - '9001:9100'
    volumes:
      - '/config/ssl:/app/ssl'
      - '/config/traefik:/etc/traefik/acme'
      - '/config/letsencrypt:/etc/letsencrypt'
      - '/data/logs/coolify:/app/logs'
      - '/data/db/sqlite3/coolify:/app/db'
      - '/data/backups/coolify:/app/backups'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/docker/daemon.json:/etc/docker/daemon.json'
    env_file:
      - $COOLIFY_ENV_FILE
